name: Scala CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  jvm:
    strategy:
      fail-fast: false
      matrix:
        scala: [2.12.19, 3.8.1]
        java: ["17", "21", "25"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up environment
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          cache: 'sbt'
          java-version: ${{ matrix.java }}

      - uses: sbt/setup-sbt@v1

      - name: Run tests
        run: sbt ++${{ matrix.scala}} fmtCheck test